name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Debug, Release]
        webrtc_support: [OFF, ON]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64 -DBUILD_EXAMPLES=ON -DBUILD_WEBRTC_SUPPORT=${{ matrix.webrtc_support }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VideoCaptureDX11-${{ matrix.build_type }}-WebRTC-${{ matrix.webrtc_support }}
        path: |
          build/lib/
          build/bin/
